---
title: "Descriptive Analysis of Medicial Organizations that Accept Medical Credit Cards"
author: "Cal Chengqi Fang"
date: "2024-01-24"
output: pdf_document
knit: >
  (function(inputFile, encoding){rmarkdown::render(inputFile, encoding=encoding, output_file="results/tables.pdf")}) 
---

```{r setup, include=FALSE}
rm(list = ls())

require(fuzzyjoin)
require(tidyverse)
require(kableExtra)
require(knitr)

opts_chunk$set(message=FALSE, warning=FALSE)

load("results/cleaned.Rdata")
```

The dataset we have cleaned included
```{r specialties, include=FALSE}
bySpe <- mcc_clean %>% 
  group_by(specialty_re) %>% 
  summarise(count = n())
```

```{r denominator, include=FALSE}
input_string <- pdftools::pdf_text(pdf="https://www.iqvia.com/-/media/iqvia/pdfs/us/publication/iqvia-us-physician-specialties-market-report-2023.pdf")[2]

# Extract the relevant text using regular expressions
temp_text <- str_extract(input_string, "(RANK)([\\s\\S]*?8,128)")

temp_rows <- str_split(temp_text, "\n\n")[[1]] %>% 
  str_trim() %>% 
  str_remove("\n")

# Split each element into columns based on long spaces
temp_columns <- str_split(temp_rows, "\\s{2,}")

# Create a dataframe, skipping the first row
denom <- as.data.frame(do.call(rbind, temp_columns[-1]))%>% 
  mutate_all(str_trim) %>%
  mutate(across(c("V3", "V4"), ~as.numeric(gsub(",", "", .)))) %>% 
  select(-V1)

# Assign column names
colnames(denom) <- c("specialty_iqvia", "phyCount", "orgCount")

# Pick out the specialty that appears in our cleaned data
denomSpe <- denom %>% 
  filter(specialty_iqvia %in% c("Internal medicine", "Family medicine", "Pediatrics", "Emergency medicine",
                                "Anesthesiology", "Obstetrics & gynecology", "General surgery", "Diagnostic radiology",
                                "Orthopedic surgery", "Ophthalmology", "Neurology", "Gastroenterology", "Dermatology", 
                                "Urology", "Physical medicine & rehabilitation"))
```

```{r fuzzyjoin, include=FALSE}
specialtyProp_iqvia <- fuzzyjoin::stringdist_join(bySpe, denomSpe, 
                                            by=c(specialty_re = "specialty_iqvia"),
                                            mode='left',
                                            method="jaccard", 
                                            distance_col='dist') %>%
  group_by(specialty_re) %>%
  filter(!(specialty_re == "Family & General Practitioner" & specialty_iqvia == "Physical medicine & rehabilitation")) %>% 
  slice_min(order_by=dist, n=1) %>% 
  filter(dist < 0.50 | specialty_re %in% c("Internist", "Imaging & Radiology")) %>% 
  filter(!(specialty_re == "Imaging & Radiology" & specialty_iqvia == "Family medicine")) %>% 
  filter(!specialty_re %in% c("Nephrology", "Podiatrist", "Nutritionist and Dietician", "Allergy/Immunologist", 
                              "Endocrinology", "General Practitioner", 
                              "Outpatient Surgery Centers", "Supplmental/Alternative Medicine", 
                              "Colorectal Surgeon/Proctologist", "Rheumatologist")) %>% 
  select(-c("phyCount", "dist")) %>% 
  mutate(prop = count / orgCount) %>% 
  arrange(prop)
```

```{r dental, include=FALSE}
# Obtain the dental office number from 2021 CBP data
## You would need to obtain an API key from http://api.census.gov/data/key_signup.html) and run following code if you don't have it set already.
## Add key to .Renviron
# Sys.setenv(CENSUS_KEY="PASTEYOURKEYHERE")
## Reload .Renviron
# readRenviron("~/.Renviron")
CBP2021 <- censusapi::getCensus(name="cbp", vintage=2021,
                                vars=c("ESTAB", "NAICS2017", "NAICS2017_LABEL"),
                                region="state:*") 

dental_denom <- CBP2021 %>% 
  filter(state <= 56) %>% # 50 states and DC correspond to the codes smaller than or equal to 56
  filter(NAICS2017 == "6212") %>% # Dentist offices correspond to 6212 in NAICS2017 system
  group_by(NAICS2017_LABEL) %>% 
  summarise(orgCount = sum(ESTAB))

dental <- bySpe %>% 
  filter(specialty_re == "Dentistry") %>% 
  cbind(dental_denom) %>% 
  mutate(prop = count / orgCount) 
```

```{r supplement, include=FALSE}
supplement_denom <- CBP2021 %>% 
  filter(state <= 56) %>% # 50 states and DC correspond to the codes smaller than or equal to 56
  filter(NAICS2017 %in% c("621310", # "Offices of Chiropractors"
                          "621340", # "Offices of Physical, Occupational and Speech Therapists, and Audiologists",
                          "446110", # "Pharmacies and Drug Stores"
                          "621610"  # "Home Health Care Services"
                          )) %>% 
  group_by(.) %>% 
  summarise(orgCount = sum(ESTAB))

supplement <- bySpe %>% 
  filter(specialty_re %in% c("Audiology", "Supplmental/Alternative Medicine")) %>% 
  group_by(.) %>% 
  summarise(specialty_re = "Supplmental/Alternative Medicine",
            count = sum(count)) %>% 
  cbind(supplement_denom) %>% 
  mutate(prop = count / orgCount) 
```

```{r podia, include=FALSE}
podiatrist_denom <- CBP2021 %>% 
  filter(state <= 56) %>% # 50 states and DC correspond to the codes smaller than or equal to 56
  filter(NAICS2017 %in% c("621391")) %>% # "Offices of Podiatrists"
  group_by(NAICS2017_LABEL) %>% 
  summarise(orgCount = sum(ESTAB))

podiatrist <- bySpe %>% 
  filter(specialty_re %in% c("Podiatrist")) %>% 
  cbind(podiatrist_denom) %>% 
  mutate(prop = count / orgCount) 
```

```{r medlab, include=FALSE}
medlab_denom <- CBP2021 %>% 
  filter(state <= 56) %>% # 50 states and DC correspond to the codes smaller than or equal to 56
  filter(NAICS2017 %in% c("621511")) %>% # "Medical Laboratories"
  group_by(NAICS2017_LABEL) %>% 
  summarise(orgCount = sum(ESTAB))

medlab <- bySpe %>% 
  filter(specialty_re %in% c("Medical Labs")) %>% 
  cbind(medlab_denom) %>% 
  mutate(prop = count / orgCount) 
```
I regrouped some of the specialties to make sure the comparison object is consistent. After such cleaning work, we have obtained the following table.

#  Table 1: MCC Penetration Rate By Specialty
```{r tab1, echo=FALSE}
tab1 <- specialtyProp_iqvia %>% 
  rbind(dental, supplement, podiatrist, medlab) %>% 
  arrange(desc(prop)) %>% 
  select(-NAICS2017_LABEL, -specialty_iqvia) %>% 
  mutate(prop = round(prop * 100, 2))

ENT_cosmetic_vision <- bySpe %>% 
  filter(specialty_re %in% c("Ear, Nose & Throat", "Cosmetic Medicine", "Vision Medicine")) %>% 
  mutate(orgCount = NA,
         prop = NA)

rest <- bySpe %>% 
  filter(!specialty_re %in% c(tab1$specialty_re, ENT_cosmetic_vision$specialty_re, 
                              "Audiology", "Supplemental/Alternative Medicine")) %>% 
  group_by(.) %>% 
  summarise(count = sum(count)) %>% 
  mutate(specialty_re = "Others",
         orgCount = NA,
         prop = NA)

tab1 <- rbind(tab1, ENT_cosmetic_vision, rest)
colnames(tab1) <- c("Specialty", "MCC Partner Number", "Total", "Percentage (%)")

# Add a total row
total <- mcc_clean %>% 
  mutate(addressLong = paste0(address, ", ", 
                              city, ", ",
                              state, " ", zipcode, ", ",
                              "USA")) %>% 
  distinct(name, addressLong, .keep_all = TRUE) %>% 
  nrow()
tab1[nrow(tab1) + 1, ] <- list("Total", total, NA, NA)

# Create the table
tab1_table <- tab1 %>% 
  kable(booktabs=TRUE, escape=FALSE, format="pipe") %>%
  kable_styling() 

# Define footnotes
footnote_text <- c("The number of total dentistry office locations, supplemental medicine office locations, podiatrist office locations, and medical lab locations are obtained from the 2021 County Business Patterns data released by US Census Bureau. All the numbers of other total specialty office locations are obtained from the 2023 IQVIA US Physician Specialties Market insights report.", 
                   "We cannot find reliable source of the estimate of total office number of cosmetic medicine, vision medicine, and ENT.")

# Add footnotes using the add_footnote function from kableExtra
add_footnote(tab1_table, label=footnote_text, notation="none")
```
\newpage
```{r tab2, echo=FALSE}
tab2 <- bySpe %>% 
  filter(!specialty_re %in% c(tab1$Specialty, "Audiology", "Supplmental/Alternative Medicine")) 

colnames(tab2) <- c("Specialty", "MCC Partner Number")
tab2 %>%
  kable(booktabs=TRUE) %>%
  kable_styling()
```

